version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: aicode
    ports: ["5433:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
